export const mockMeResponse = {
  id: 'test-user',
  username: 'test-user',
  groups: [
    {
      id: 'groupId1',
      displayName: 'c-Group 1',
      name: 'group1',
      admins: null,
      quotaCpu: null,
      quotaGpu: null,
      quotaMemory: null,
      projectQuotaCpu: null,
      projectQuotaGpu: null,
      projectQuotaMemory: null,
      datasets: [],
      resourceStatus: {
        cpuUsage: 0,
        memUsage: 0,
        gpuUsage: 0,
        __typename: null,
      },
      users: null,
      enabledDeployment: true,
      enabledSharedVolume: true,
      jobDefaultActiveDeadlineSeconds: 86400,
      sharedVolumeCapacity: null,
      launchGroupOnly: null,
      __typename: 'Group',
      instanceTypes: [
        {
          id: 'g-it1',
          name: 'IT1',
          displayName: 'group1 it',
          description: 'Basic instance.',
          spec: null,
          global: null,
          gpuLimit: 0,
          memoryLimit: 4,
          cpuLimit: 0.5,
          __typename: null,
        },
        {
          id: 'g-it2',
          name: 'AIT1',
          displayName: 'A group1 it',
          description: 'A Basic instance.',
          spec: null,
          global: null,
          gpuLimit: 0,
          memoryLimit: 4,
          cpuLimit: 0.5,
          __typename: null,
        },
      ],
      images: [
        {
          id: 'image-1',
          name: 'image-test',
          displayName: 'Group image test',
          description: null,
          groupName: 'group1',
          isReady: null,
          url: 'cpucpu',
          urlForGpu: null,
          useImagePullSecret: null,
          spec: null,
          global: null,
          type: 'cpu',
          __typename: null,
        },
      ],
    },
    {
      id: 'groupId2',
      displayName: 'Group 2',
      name: 'group2',
      admins: null,
      quotaCpu: null,
      quotaGpu: null,
      quotaMemory: null,
      projectQuotaCpu: null,
      projectQuotaGpu: null,
      projectQuotaMemory: null,
      datasets: null,
      resourceStatus: {
        cpuUsage: 1,
        memUsage: 0,
        gpuUsage: 0,
        __typename: null,
      },
      users: null,
      enabledDeployment: null,
      enabledSharedVolume: null,
      jobDefaultActiveDeadlineSeconds: null,
      sharedVolumeCapacity: null,
      launchGroupOnly: null,
      __typename: 'Group',
      instanceTypes: [
        {
          id: 'ggit1',
          name: 'IT1',
          displayName: 'group2 it',
          description: null,
          spec: null,
          global: null,
          gpuLimit: null,
          memoryLimit: null,
          cpuLimit: null,
          __typename: null,
        },
      ],
      images: [
        {
          id: 'ggit2',
          name: 'IT1',
          displayName: 'group2 im',
          description: null,
          groupName: null,
          isReady: null,
          url: null,
          urlForGpu: null,
          useImagePullSecret: null,
          spec: null,
          global: null,
          type: null,
          __typename: null,
        },
      ],
    },
    {
      id: 'everyone',
      displayName: 'Group DisplayName',
      name: 'everyone',
      admins: null,
      quotaCpu: null,
      quotaGpu: null,
      quotaMemory: null,
      projectQuotaCpu: null,
      projectQuotaGpu: null,
      projectQuotaMemory: null,
      datasets: null,
      resourceStatus: null,
      users: null,
      enabledDeployment: null,
      enabledSharedVolume: null,
      jobDefaultActiveDeadlineSeconds: null,
      sharedVolumeCapacity: null,
      launchGroupOnly: null,
      __typename: 'Group',
      instanceTypes: [
        {
          id: 'everyone-it',
          name: 'it',
          displayName: 'gpu0',
          description: null,
          spec: null,
          global: null,
          gpuLimit: 0,
          memoryLimit: 4,
          cpuLimit: 0.5,
          __typename: null,
        },
        {
          id: 'everyone-it2',
          name: 'it',
          displayName: 'gpu1',
          description: null,
          spec: null,
          global: null,
          gpuLimit: 1,
          memoryLimit: null,
          cpuLimit: null,
          __typename: null,
        },
      ],
      images: [
        {
          id: 'everyone-image',
          name: 'b-cpu',
          displayName: 'b-cpu',
          description: null,
          groupName: null,
          isReady: null,
          url: null,
          urlForGpu: null,
          useImagePullSecret: null,
          spec: null,
          global: null,
          type: 'cpu',
          __typename: null,
        },
        {
          id: 'everyone-image2',
          name: 'a-gpu',
          displayName: 'a-gpu',
          description: null,
          groupName: null,
          isReady: null,
          url: null,
          urlForGpu: null,
          useImagePullSecret: null,
          spec: null,
          global: null,
          type: 'gpu',
          __typename: null,
        },
        {
          id: 'everyone-image3',
          name: 'c-img',
          displayName: 'c-img',
          description: null,
          groupName: null,
          isReady: null,
          url: null,
          urlForGpu: null,
          useImagePullSecret: null,
          spec: null,
          global: null,
          type: 'both',
          __typename: null,
        },
      ],
    },
  ],
  __typename: 'MePayload',
  isCurrentGroupAdmin: false,
};
