
export enum ErrorCodes {
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  REQUEST_BODY_INVALID = 'REQUEST_BODY_INVALID',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  EXCEED_QUOTA_ERROR = 'EXCEED_QUOTA',
  NOT_AUTH_ERROR = 'NOT_AUTH',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
}
