
export enum ErrorCodes {
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  MUTATION_IN_READONLY = 'MUTATION_IN_READONLY',
  REQUEST_BODY_INVALID = 'REQUEST_BODY_INVALID',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED'
}
