export const mlflow = {
  trackingUri: 'http://localhost:5000',
  uiUrl: 'http://localhost:5000',
  trackingEnvs: [
    {
      name: 'FOO',
      value: 'bar'
    },
    {
      name: 'BAR',
      value: 'foo'
    }
  ],
  artifactEnvs: [
    {
      name: 'FOO_A',
      value: 'bar'
    },
    {
      name: 'BAR_A',
      value: 'foo'
    }
  ]
};

export const groups = [
  {
    id: 'groupId1',
    name: 'group1',
    mlflow,
    displayName: 'c-Group 1',
    enabledDeployment: true,
    maxDeploy: 10,
    enabledSharedVolume: true,
    users: null,
    jobDefaultActiveDeadlineSeconds: 86400,
    sharedVolumeCapacity: null,
    launchGroupOnly: null,
    instanceTypes: [
      {
        id: 'g-it1',
        name: 'IT1',
        displayName: 'group1 it',
        description: 'Basic instance.',
        spec: null,
        global: null,
        gpuLimit: 0,
        memoryLimit: 4,
        cpuLimit: 0.5,
      },
      {
        id: 'g-it2',
        name: 'AIT1',
        displayName: 'A group1 it',
        description: 'A Basic instance.',
        spec: null,
        global: null,
        gpuLimit: 0,
        memoryLimit: 4,
        cpuLimit: 0.5,
      },
    ],
    images: [
      {
        id: 'image-1',
        name: 'image-test',
        displayName: 'Group image test',
        description: null,
        groupName: 'group1',
        isReady: null,
        url: 'cpucpu',
        urlForGpu: null,
        useImagePullSecret: null,
        spec: null,
        global: null,
        type: 'cpu',
      },
    ],
  },
  {
    id: 'groupId2',
    displayName: 'Group 2',
    name: 'group2',
    admins: null,
    quotaCpu: null,
    quotaGpu: null,
    quotaMemory: null,
    projectQuotaCpu: null,
    projectQuotaGpu: null,
    projectQuotaMemory: null,
    datasets: null,
    resourceStatus: {
      cpuUsage: 1,
      memUsage: 0,
      gpuUsage: 0,
    },
    users: null,
    enabledDeployment: null,
    enabledSharedVolume: null,
    jobDefaultActiveDeadlineSeconds: null,
    sharedVolumeCapacity: null,
    launchGroupOnly: null,
    instanceTypes: [
      {
        id: 'ggit1',
        name: 'IT1',
        displayName: 'group2 it',
        description: null,
        spec: null,
        global: null,
        gpuLimit: null,
        memoryLimit: null,
        cpuLimit: null,
      },
    ],
    images: [
      {
        id: 'ggit2',
        name: 'IT1',
        displayName: 'group2 im',
        description: null,
        groupName: null,
        isReady: null,
        url: null,
        urlForGpu: null,
        useImagePullSecret: null,
        spec: null,
        global: null,
        type: null,
      },
    ],
  },
  {
    id: 'everyone',
    displayName: 'Group DisplayName',
    name: 'everyone',
    admins: null,
    quotaCpu: null,
    quotaGpu: null,
    quotaMemory: null,
    projectQuotaCpu: null,
    projectQuotaGpu: null,
    projectQuotaMemory: null,
    datasets: null,
    resourceStatus: null,
    users: null,
    enabledDeployment: null,
    enabledSharedVolume: null,
    jobDefaultActiveDeadlineSeconds: null,
    sharedVolumeCapacity: null,
    launchGroupOnly: null,
    instanceTypes: [
      {
        id: 'everyone-it',
        name: 'it',
        displayName: 'gpu0',
        description: null,
        spec: null,
        global: null,
        gpuLimit: 0,
        memoryLimit: 4,
        cpuLimit: 0.5,
      },
      {
        id: 'everyone-it2',
        name: 'it',
        displayName: 'gpu1',
        description: null,
        spec: null,
        global: null,
        gpuLimit: 1,
        memoryLimit: null,
        cpuLimit: null,
      },
    ],
    images: [
      {
        id: 'everyone-image',
        name: 'b-cpu',
        displayName: 'b-cpu',
        description: null,
        groupName: null,
        isReady: null,
        url: null,
        urlForGpu: null,
        useImagePullSecret: null,
        spec: null,
        global: null,
        type: 'cpu',
      },
      {
        id: 'everyone-image2',
        name: 'a-gpu',
        displayName: 'a-gpu',
        description: null,
        groupName: null,
        isReady: null,
        url: null,
        urlForGpu: null,
        useImagePullSecret: null,
        spec: null,
        global: null,
        type: 'gpu',
      },
    ],
  },
];

export default groups;
