export const system = {
  license: {
    licenseStatus: 'unexpired',
    startedAt: '2021-06-30T00:00:00Z',
    expiredAt: '2021-12-31T12:59:00Z',
    licensedTo: 'InfuseAI',
    maxNode: 1000,
    maxModelDeploy: 1000,
    maxGroup: 9999,
    usage: {
      maxGroup: 68,
      maxNode: 5,
      maxModelDeploy: 109,
      __typename: 'Usage',
    },
    __typename: 'License',
  },
  org: {
    name: 'InfuseAI',
    logo: {
      contentType: null,
      name: null,
      size: 0,
      url: 'https://i.imgur.com/CDz3JAY.png',
    },
    __typename: 'Org',
  },
  defaultUserVolumeCapacity: 20,
  timezone: {
    name: 'Asia/Taipei',
    offset: 8,
    __typename: 'Timezone',
  },
  smtp: {
    host: 'smtp.sendgrid.net',
    port: 465,
    fromDisplayName: 'InfuseAI',
    from: 'demo@infuseai.io',
    replyToDisplayName: null,
    replyTo: null,
    envelopeFrom: null,
    enableSSL: true,
    enableStartTLS: false,
    enableAuth: true,
    username: 'apikey',
    password: '**********',
    __typename: 'Smtp',
  },
  __typename: 'System',
};
