apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instancetypes.primehub.io
spec:
  conversion:
    strategy: None
  group: primehub.io
  names:
    kind: InstanceType
    listKind: InstanceTypeList
    plural: instancetypes
    singular: instancetype
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
        properties:
          metadata:
            type: object
          spec:
            properties:
              description:
                type: string
              displayName:
                type: string
              limits.cpu:
                type: number
              limits.memory:
                type: string
              limits.nvidia.com/gpu:
                type: integer
              requests.memory:
                type: string
              requests.cpu:
                type: number
              nodeSelector:
                x-kubernetes-preserve-unknown-fields: true
                type: object
              tolerations:
                type: array
                items:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
            required:
            - limits.cpu
            - limits.memory
            type: object
        type: object
    served: true
    storage: true
