export interface Props {
  onChange: Function,
  refId: any,
  value: any,
  uiParams: any,
  deploy: Function,
  routes: Array<string>,
  goTo: Function,
  reset: Function,
  intl: any,
  keyName: string,
  items: any,
  showPagination: any,
  disabled: any,
  title: string,
  rootValue: Object,
  form: any,
  size: string,
  routerParams: any
}